// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Web_quan_ly_nhan_su.Context;

#nullable disable

namespace Web_quan_ly_nhan_su.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517173606_AddThuocTinhLuong")]
    partial class AddThuocTinhLuong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.DanhMucKienThuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Vector>("VectoNoiDung")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucKienThuc", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LichCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileDinhKemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDungCongViec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichCongTac");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("BaoHiemThatNghiep")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaoHiemXaHoi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaoHiemYTe")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KhauTru")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("numeric");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TienTangCa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LuuTruFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("text");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LuuTruFile", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<string>("MinhChungUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NghiPhep", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceVector")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVienVaiTro", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien", "MaVaiTro");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanVienVaiTro", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhomChat", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("AnhNhom")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNhom");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("NhomChat", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhongBan"));

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaNhom");

                    b.ToTable("ThanhVienNhom", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTinNhan"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("integer");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("integer");

                    b.Property<int?>("NguoiNhanId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNhom");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.TinNhanNhom", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTinNhan"));

                    b.Property<int>("MaNhom")
                        .HasColumnType("integer");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNhom");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("TinNhanNhom", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MaCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ChamCong", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LichCongTac", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany("LichCongTacs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.Luong", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LuuTruFile", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NghiPhep", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVienVaiTro", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany("NhanVienVaiTro")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_quan_ly_nhan_su.Models.VaiTro", "VaiTro")
                        .WithMany("NhanVienVaiTro")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhomChat", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany("NhomDaThamGia")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_quan_ly_nhan_su.Models.NhomChat", "NhomChat")
                        .WithMany("DanhSachThanhVien")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("NhomChat");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.TinNhan", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhomChat", "NhomChat")
                        .WithMany()
                        .HasForeignKey("MaNhom");

                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NguoiGui")
                        .WithMany("TinNhanDaGui")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NguoiNhan")
                        .WithMany("TinNhanDaNhan")
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");

                    b.Navigation("NhomChat");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.TinNhanNhom", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhomChat", "NhomChat")
                        .WithMany("DanhSachTinNhanNhom")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NhomChat");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.Navigation("LichCongTacs");

                    b.Navigation("NhanVienVaiTro");

                    b.Navigation("NhomDaThamGia");

                    b.Navigation("TinNhanDaGui");

                    b.Navigation("TinNhanDaNhan");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhomChat", b =>
                {
                    b.Navigation("DanhSachThanhVien");

                    b.Navigation("DanhSachTinNhanNhom");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.VaiTro", b =>
                {
                    b.Navigation("NhanVienVaiTro");
                });
#pragma warning restore 612, 618
        }
    }
}
