// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web_quan_ly_nhan_su.Context;

#nullable disable

namespace Web_quan_ly_nhan_su.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("KhauTru")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("numeric");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LuuTruFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("text");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LuuTruFile", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiNghi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NghiPhep", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceVector")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVienVaiTro", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien", "MaVaiTro");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanVienVaiTro", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhongBan"));

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MaCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.ChamCong", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.Luong", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.LuuTruFile", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NghiPhep", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVienVaiTro", b =>
                {
                    b.HasOne("Web_quan_ly_nhan_su.Models.NhanVien", "NhanVien")
                        .WithMany("NhanVienVaiTro")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_quan_ly_nhan_su.Models.VaiTro", "VaiTro")
                        .WithMany("NhanVienVaiTro")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.NhanVien", b =>
                {
                    b.Navigation("NhanVienVaiTro");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Web_quan_ly_nhan_su.Models.VaiTro", b =>
                {
                    b.Navigation("NhanVienVaiTro");
                });
#pragma warning restore 612, 618
        }
    }
}
