name: Deploy To Fly.io Automatically
on:
  push:
    branches:
      - master  # Hoặc đổi thành master tùy thuộc vào tên nhánh chính của ông

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flyctl CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Execute Deploy Command
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
